### ISSUE TITLE
[Feature Request] Add support for Pro Drums Mode

### ISSUE THREAD

**Issue by ebellumat** [Dirtmigurt/ConvertHero#8]
Hello! Moonscraper Chart Editor have and special mode called "Pro Drums" that is used in Rock band, Clone Hero and Beat Smith Drum Songs, that consists in 3 colors that can be uses as cymbals or toms.

This screenshot shows these gold notes in blue and green lanes, this notes are read in the games as cymbal notes.

![image](https://user-images.githubusercontent.com/26942680/88957061-b0a71280-d274-11ea-9bf5-fe91018d1612.png)

This is the final result on Beat Smith as example with this special mode.

https://youtu.be/F1tdru0giPw

Can you add the support to add the flag on cymbal notes on chart file? You can check the discussion here.

https://github.com/FireFox2000000/Moonscraper-Chart-Editor/issues/37 

And more details here.

http://docs.c3universe.com/rbndocs/index.php?title=Drum_Authoring#Displaying_Tom_Gems

And you can check this chart as an example.

https://drive.google.com/drive/folders/1JWzjJ7pxckQQG7UyUR80hOAOTSmNJQTl

I hope this links can help on implementation!

**Comment by Dirtmigurt** [comment]
I've only ever played Guitar Hero's 5 lane drums and assumed thats what people were interested in.
I have looked into what RB Pro drums are and how they are represented, and it seems 4 Lane + Pro is the way that the Customs community is going so I will change the implementation to support that.

**Comment by ebellumat** [comment]
Thanks for your time and your reply! 

And, what you think about Beat Smith?

You think will be a good game? :D

**Comment by FireFox2000000** [comment]
I'm keeping track of the changes we're making to the chart format to support pro drums outside of the midi spec which you can find here-
https://docs.google.com/document/d/1v2v0U-9HQ5qHeccpExDOLJ5CMPZZ3QytPmAG5WF0Kzs

Doubles kicks will most likely be added on note 32, but will only update the spec once that's properly in, in case there's any finals changes we make.
